version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - 4567:4567
    environment:
      - TRAVIS_TOKEN=
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/by:cached
      - bundler:/usr/local/bundle

volumes:
  bundler:
